// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikieturdialxjoolthym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlraWV0dXJkaWFseGpvb2x0aHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzg2NTgsImV4cCI6MjA3MjM1NDY1OH0.X9E5GiB7pRmqD-z0V7zXFIE6vx9jDai1wkR60MltYWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});