// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syinnrlzvfnpxbebgtew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aW5ucmx6dmZucHhiZWJndGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM1MDksImV4cCI6MjA2NTU3OTUwOX0.fXfiMiJAW3V-RztkazKwkpjc1erL5a8MLyLFcz1afj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);